In [39]:
%pylab inline
from pandas import Series, DataFrame
import pandas as pd

Populating the interactive namespace from numpy and matplotlib


《[利用Python进行数据分析](https://book.douban.com/subject/25779298/)》
作者: Wes McKinney
译者: 唐学韬


Pandas中两个主要的数据结构是 `Series` 和 `DataFrame`，两个数据结构中都使用了索引(`Index`)对象。


# Series

Series是一组带索引的数组。包含一组数据（各种NumPy数据类型）和与之相关的一组数据标签（即索引）。

可以用index和values分别规定索引和值。如果不规定索引，会自动创建 0 到 N-1 索引。

## 最简单的 Series

In [40]:
#  只包含一组数据的 Series
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [41]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [42]:
obj.values

array([ 4,  7, -5,  3])

## 指定索引

In [43]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

##  通过索引获取数据

In [44]:
#  取单行数据
obj2['d']

4

In [45]:
# 取多行数据
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

## 按条件获取数据

In [46]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

## 数组运算

 对数组进行计算，只改变值，不会改变索引

In [47]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [48]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

## 改变索引

In [49]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [50]:
obj2.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj2

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## 作为Dictionary

可以将 Series 看作一个定长有序字典。

In [51]:
'b' in obj2

False

In [52]:
#  通过 Dictionary 直接创建 Series
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [53]:
# 重建索引，并按索引筛选数据
# 注意，索引 `California`  对应的值为 NaN
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

## 数据检查

In [54]:
pd.isnull(obj4) # 等价于 obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [55]:
pd.notnull(obj4) #  等价于 obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

## 自动对齐索引

Series很重要的功能就是按照索引自动对齐。

In [56]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [57]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [58]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

##  命名

Series 自身和索引都可以命名。这个设计对于 Pandas 其他模块很重要。

In [59]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [60]:
obj4.index

Index(['California', 'Ohio', 'Oregon', 'Texas'], dtype='object', name='state')

# DataFrame

DataFrame 是一种表格型结构，含有一组有序的列，每一列可以是不同的数据类型。

DataFrame 可以看做是共用索引的、由Series组成的字典。其中，共用的索引是整个 DataFrame 的行索引，而各个 Series 的名字作为列索引。

DataFrame面向行和列的操作基本是平衡的。其实，DataFrame中的数据是以一个或者多个二维块存放的（不是列表、字典或者其他）。

##  创建 DataFrame

In [92]:
#  使用字典创建
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [66]:
# 更改列顺序
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [68]:
# 与行索引的机制类似，找不到的列，会用 NaN 填充
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

##  得到列

In [70]:
# 列是关于 Series 的字典
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [72]:
# 获取某一列
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [74]:
# 也可以用属性的方式获取 DataFrame 中的某一列
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [78]:
#  获取多个列，还是 DataFrame, 此时为“切片”操作
frame2[['state','year']]

state  year
one      Ohio  2000
two      Ohio  2001
three    Ohio  2002
four   Nevada  2001
five   Nevada  2002

##  得到行

通过索引可以得到 DataFrame 的一行，行也是一个 Series.

In [79]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

## 按列赋值

In [81]:
# 整列赋相同值
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [84]:
# 用一个 array 或 narray 对列赋值
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [86]:
# 使用 Series，可以根据索引对列精确赋值
# 注意其中的空值
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

## 增加和删除列

In [90]:
# 对不存在的列赋值会增加列
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [91]:
# 使用 `del` 删除列
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

## 转置

In [93]:
frame2.T

one   two three    four    five
year   2000  2001  2002    2001    2002
state  Ohio  Ohio  Ohio  Nevada  Nevada
pop     1.5   1.7   3.6     2.4     2.9
debt    NaN  -1.2   NaN    -1.5    -1.7

## 更多创建方法

In [95]:
#  使用二维字典创建
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [96]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [97]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

## 为索引和列命名

In [98]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

## DataFrame 的值

In [101]:
# 返回 ndarray
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [102]:
# 类型不同时，自动转换为最抽象的类型
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

#  索引对象

In [103]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [104]:
index[1:]

Index(['b', 'c'], dtype='object')

In [109]:
# Index 里面的数据不能更改
# index[1] = 'd'

In [113]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

In [114]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [115]:
'Ohio' in frame3.columns

True

In [116]:
2003 in frame3.index

False

Index 不是数组，也不是 Series（看起来像）。Index 支持的一些方法如下：

- append  连接另一个 Index
- diff  计算差集
- intersection 计算交集
- union 计算并集
- isin 是否全包含
- delete 删除 i  初的元素，返回一个新的 Index
- drop 删除传入的值，返回一个新的 Index
- insert 插入到 i 处
- is_monotonic 是否各元素都大于等于前一个元素（顺序排列）
- is_unique 是否没有重复值
- unique 返回唯一值的数组