In [1]:
%pylab inline
from pandas import Series, DataFrame
import pandas as pd

Populating the interactive namespace from numpy and matplotlib


《[利用Python进行数据分析](https://book.douban.com/subject/25779298/)》
作者: Wes McKinney
译者: 唐学韬


# 重建索引

Pandas 对象的重建索引（`reindex()`)，会根据索引创建一个新的对象。

In [2]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [5]:
# 如果传入的索引值在数据里不存在，则不会报错，而是添加缺失值的新行
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [6]:
#如果不想用缺失值，可以用 fill_value 参数指定填充值
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [13]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
# method 指定填充新值采用的差值方法
# ffill 或 pad 实现用前值填充(forward fill)
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [16]:
# bfill 或 backfill 实现用后值填充
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [17]:
# #DataFrame 的reindex可以修改行、列或者两个都改

frame = DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
                  columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [19]:
# 默认更改行索引
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [20]:
# 使用 columns 更改列索引
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [21]:
# 同时更改行和列索引
# 注意插值只能用在行上
frame.reindex(index=['a', 'b', 'c', 'd'], method='ffill',
              columns=states)

Texas  Utah  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [22]:
# 使用ix的标签索引功能，重新索引变得比较简洁
# 等价于 frame.reindex(index=['a', 'b', 'c', 'd'], columns=states)
frame.ix[['a', 'b', 'c', 'd'], states]


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

## 丢弃指定轴上的项

In [23]:
#  drop() 方法：通过索引数组或列表丢弃多个项，返回一个新的对象
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [24]:
# 丢弃多项
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [25]:
# 对于 DataFrame
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [27]:
#  丢弃行
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
# 丢弃一列
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [29]:
# 丢弃多列
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

## 索引、选取和过滤

In [30]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj


a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [35]:
#  通过索引选取, 以下两种方式等价
print(obj['b'])
print(obj[1])

1.0
1.0


In [39]:
#  连续切片
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [40]:
# 通过索引选取
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [41]:
# 通过序号选取
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [42]:
# 条件筛选
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [46]:
# 针对索引的条件筛选
obj['b':'d']

b    1.0
c    2.0
d    3.0
dtype: float64

In [49]:
# 筛选并赋值
obj['b':'d'] = 5
obj

a    0.0
b    5.0
c    5.0
d    5.0
dtype: float64

In [51]:
# 对于 DataFrame
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [52]:
# 选取列
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [53]:
# 选取多列
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [55]:
# 
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [56]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [57]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [59]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [63]:
# 选择一行中的一部分
data.ix['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [64]:
# 选择多行中的一部分
data.ix[['Colorado', 'Utah'], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [66]:
# 一整行
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [67]:
data.ix[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [68]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## 算术运算和数据对齐

Pandas 在对 Series 和 DataFrame 进行算术运算时，能够根据索引自动对齐,其中索引不重合的部分值为NaN。

+，-，*，/ 对应的函数分别为 `add()`, `sub()`, `mul()`, `div()`。

In [69]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [70]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [71]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [72]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [73]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [74]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [75]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### 在算术方法中填充值

In [76]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [77]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [78]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [79]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [80]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### DataFrame 和 Series 之间的运算

In [81]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [82]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [83]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [84]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.ix[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [85]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [91]:
# 将Series的索引匹配到DataFrame的列，然后进行计算，再沿着行一直向下广播
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [92]:
series2 = Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [95]:
#  非共有的列，自动填充
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [88]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [89]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [96]:
# 使用算术运算方法，可以指定轴，从而实现匹配行且在列上广播
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 函数应用和映射

In [97]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [98]:
frame

b         d         e
Utah    0.155111 -0.301627  0.034083
Ohio   -0.003312  0.807804 -1.046114
Texas   1.983635 -0.667859  1.657091
Oregon  1.633512 -2.041568  0.820017

In [100]:
# 求绝对值函数
np.abs(frame)

b         d         e
Utah    0.155111  0.301627  0.034083
Ohio    0.003312  0.807804  1.046114
Texas   1.983635  0.667859  1.657091
Oregon  1.633512  2.041568  0.820017

In [103]:
#另一种常见的做法是：将一个函数应用到行或者列上,用apply方法
# 默认应用到行，广播到列
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.986947
d    2.849372
e    2.703205
dtype: float64

In [104]:
# 通过指定 axis，可以应用到列，广播到行
frame.apply(f, axis=1)

Utah      0.456738
Ohio      1.853918
Texas     2.651494
Oregon    3.675080
dtype: float64

In [105]:
# 传递的函数还可以返回 Series
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.003312 -2.041568 -1.046114
max  1.983635  0.807804  1.657091

In [109]:
# applymap:  应用到元素（而不是行和列）
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah     0.16  -0.30   0.03
Ohio    -0.00   0.81  -1.05
Texas    1.98  -0.67   1.66
Oregon   1.63  -2.04   0.82

In [111]:
# 因为 frame 调用了 Series 的 map()函数
frame['e'].map(format)

Utah       0.03
Ohio      -1.05
Texas      1.66
Oregon     0.82
Name: e, dtype: object

## 排序和排名

主要的函数包括：

- sort_index(): 按索引排序
- sort_values(): 按值排序
- rank(): 排名

In [113]:
#用sort_index函数对行、列的索引进行排序
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [114]:
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [115]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [116]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [118]:
#  对值排序，使用 sort_values()
obj = Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [119]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [120]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [122]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [123]:
frame.sort_values(by=['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [128]:
#rank函数返回从小到大排序的下标，对于平级的数，rank是通过“为各组分配一个平均排名”的方式破坏平级关系
#下标从1开始
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [125]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [129]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [130]:
frame = DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                   'c': [-2, 5, 8, -2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [131]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

## 带有重复值的轴索引

In [132]:
obj = Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [133]:
#用is_unique看是否唯一
obj.index.is_unique

False

In [135]:
# #对于重复值的索引，选取的话返回一个Series
obj['a']

a    0
a    1
dtype: int64

In [137]:
# 唯一的索引返回一个标量
obj['c']

4

In [138]:
df = DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -0.146504 -0.442410 -1.044600
a -1.243650  0.281303  0.485324
b  1.040675  0.479036 -0.753287
b -1.571259  0.194030  0.517437

In [139]:
df.ix['b']

0         1         2
b  1.040675  0.479036 -0.753287
b -1.571259  0.194030  0.517437