《[利用Python进行数据分析](https://book.douban.com/subject/25779298/)》读书笔记。
 
 [第7章](/2017/03/10/python_data_analysis7.html)  第3节：数据转换

所有用到的数据可以从[作者的 github](https://github.com/wesm/pydata-book)下载。


In [1]:
%pylab inline
import pandas as pd
from pandas import Series, DataFrame
import json

Populating the interactive namespace from numpy and matplotlib


重排之后，下面介绍数据的过滤、清理、以及其他转换工作。

# 去除重复数据

In [2]:
data = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [3]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [9]:
# 得到去重之后的DataFrame，这是非常常用的
data.drop_duplicates()

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [10]:
# 可以选定需要去重的列
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
3  two   3   3

In [11]:
# 默认保留第一次出现的行,  可以设定为最后一个
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

# 用函数或者映射(mapping)进行数据转换

可以实现根据值进行转换。

In [12]:
data = DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami',
                           'corned beef', 'Bacon', 'pastrami', 'honey ham',
                           'nova lox'],
                  'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [16]:
#  添加一个肉类到动物的映射
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [18]:
# Series的map方法可以接受一个函数或含有映射关系的字典型对象
# 为了保证映射正确，先转换大小写。 这种方法很常用
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [19]:
# 也可以用一个函数实现上述功能
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

# 替换值

 使用 `replace()`函数，可以更简单的实现值替换。

In [20]:
data = Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [21]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [22]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [23]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [24]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

# 重命名轴索引

与值一样，轴标签页可以用 `map()`函数进行映射。

In [25]:
data = DataFrame(np.arange(12).reshape((3, 4)),
                 index=['Ohio', 'Colorado', 'New York'],
                 columns=['one', 'two', 'three', 'four'])

In [26]:
data.index.map(str.upper)

array(['OHIO', 'COLORADO', 'NEW YORK'], dtype=object)

In [27]:
data.index = data.index.map(str.upper)
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [28]:
# 对于轴，与 replace()类似的函数是 rename()
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [29]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [31]:
# inplace 指定 就地修改，而无需新建一个数据结构
_ = data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

# 离散化和面元划分

为了便于分析，连续数据常常被离散化或拆分为面元（bin），即分组。

In [32]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [38]:
# 使用 cut(), 将 ages 分为 18-25，25-35.。。等几个面元(bin)
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [39]:
# 返回的是一个特殊的Categorical对象，可以看作是表示面元名称的字符串。 
# 含有一个表示不同分类名称的 categories 数组以及一个 codes 属性.
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [40]:
cats.categories

Index(['(18, 25]', '(25, 35]', '(35, 60]', '(60, 100]'], dtype='object')

In [41]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [43]:
#  默认为“左开右闭”，可以通过 right=False 指定“左闭右开”
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, object): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [46]:
# 指定分组标签（面元名称）
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [48]:
# 按数量均分为4组，精度为2位（而不是按值划分）
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.74, 0.98], (0.49, 0.74], (0.25, 0.49], (0.74, 0.98], (0.25, 0.49], ..., (0.00071, 0.25], (0.00071, 0.25], (0.74, 0.98], (0.00071, 0.25], (0.74, 0.98]]
Length: 20
Categories (4, object): [(0.00071, 0.25] < (0.25, 0.49] < (0.49, 0.74] < (0.74, 0.98]]

In [49]:
# qcut: 根据样本分位数切分。如下：根据4分位数切成4份
data = np.random.randn(1000) # Normally distributed
cats = pd.qcut(data, 4) # Cut into quartiles
cats

[(0.0103, 0.682], [-3.378, -0.647], (0.0103, 0.682], (-0.647, 0.0103], (0.0103, 0.682], ..., (0.0103, 0.682], (-0.647, 0.0103], (-0.647, 0.0103], [-3.378, -0.647], (0.0103, 0.682]]
Length: 1000
Categories (4, object): [[-3.378, -0.647] < (-0.647, 0.0103] < (0.0103, 0.682] < (0.682, 3.119]]

In [51]:
pd.value_counts(cats)

(0.682, 3.119]      250
(0.0103, 0.682]     250
(-0.647, 0.0103]    250
[-3.378, -0.647]    250
dtype: int64

In [52]:
#  根据设定的分位数切分
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.0103, 1.294], [-3.378, -1.276], (0.0103, 1.294], (-1.276, 0.0103], (0.0103, 1.294], ..., (0.0103, 1.294], (-1.276, 0.0103], (-1.276, 0.0103], (-1.276, 0.0103], (0.0103, 1.294]]
Length: 1000
Categories (4, object): [[-3.378, -1.276] < (-1.276, 0.0103] < (0.0103, 1.294] < (1.294, 3.119]]

# 检测和过滤离群点

离群点（outlier）的过滤或变换运算在很大程度上其实就是数组运算。

In [53]:
np.random.seed(12345)
data = DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [55]:
# 第4列中，绝对值>3的行
col = data[3]
col[np.abs(col) > 3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [56]:
# 全部含有超过3或-3的值的行
data[(np.abs(data) > 3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [58]:
# 修改值
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

# 排列和随机采样

In [59]:
df = DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [62]:
# 返回一个随机排列
sampler = np.random.permutation(5)
sampler

array([1, 3, 0, 2, 4])

In [63]:
# 在基于ix的索引操作或者take函数中使用该数组
df.take(sampler)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11
4  16  17  18  19

In [64]:
# 进行截取
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19

In [65]:
bag = np.array([5, 7, -1, 6, 4])
sampler = np.random.randint(0, len(bag), size=10)

In [66]:
sampler

array([3, 0, 4, 1, 1, 2, 3, 0, 1, 2])

In [67]:
draws = bag.take(sampler)
draws

array([ 6,  5,  4,  7,  7, -1,  6,  5,  7, -1])

# 计算指标/哑变量

一种常用的用于统计建模或机器学习的转换方式是：将分类变量（categorical variable）转换为“哑变量矩阵”(dummy matrix)或“指标矩阵”（indicator matrix）。

如果DataFrame的某一列有k各不同的值，可以派生出一个k列的矩阵或者DataFrame（值为1和0）。

这样的做法在下一章（第八章）的地图的例子中有体现。

In [70]:
df = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                'data1': range(6)})
df

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [71]:
# 得到哑变量DataFrame
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [72]:
# 给指标列加上一个前缀
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [75]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('data/ch02/movielens/movies.dat', sep='::', header=None,
                        names=mnames,engine='python')
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [77]:
#  将 `|` 分隔的 genres 拆分
genre_iter = (set(x.split('|')) for x in movies.genres)
genres = sorted(set.union(*genre_iter))
genres

['Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [83]:
#  构建一个全零的 DataFrame
dummies = DataFrame(np.zeros((len(movies), len(genres))), columns=genres)
dummies.head()

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
1     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
2     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
4     0.0        0.0        0.0         0.0     0.0    0.0          0.0   

   Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
1    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
2    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
3    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
4    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   

   Thriller  War  Western  
0       0.0  0.0      0.0  
1       0.0  0.0      0.0  
2       0.0  0.0      0.0  
3       0.0  0.0      0.0  
4       0.0  0.0      0.0

In [85]:
#  设置标记
for i, gen in enumerate(movies.genres):
    dummies.ix[i, gen.split('|')] = 1

In [86]:
# 将标记合并到movies
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic

movie_id                                              title  \
0            1                                   Toy Story (1995)   
1            2                                     Jumanji (1995)   
2            3                            Grumpier Old Men (1995)   
3            4                           Waiting to Exhale (1995)   
4            5                 Father of the Bride Part II (1995)   
5            6                                        Heat (1995)   
6            7                                     Sabrina (1995)   
7            8                                Tom and Huck (1995)   
8            9                                Sudden Death (1995)   
9           10                                   GoldenEye (1995)   
10          11                     American President, The (1995)   
11          12                 Dracula: Dead and Loving It (1995)   
12          13                                       Balto (1995)   
13          14                                       Nixon (1995)   
14          15                            Cutthroat Island (1995)   
15          16                                      Casino (1995)   
16          17                       Sense and Sensibility (1995)   
17          18                                  Four Rooms (1995)   
18          19              Ace Ventura: When Nature Calls (1995)   
19          20                                 Money Train (1995)   
20          21                                  Get Shorty (1995)   
21          22                                     Copycat (1995)   
22          23                                   Assassins (1995)   
23          24                                      Powder (1995)   
24          25                           Leaving Las Vegas (1995)   
25          26                                     Othello (1995)   
26          27                                Now and Then (1995)   
27          28                                  Persuasion (1995)   
28          29                  City of Lost Children, The (1995)   
29          30  Shanghai Triad (Yao a yao yao dao waipo qiao) ...   
...        ...                                                ...   
3853      3923                           Return of the Fly (1959)   
3854      3924                                Pajama Party (1964)   
3855      3925                      Stranger Than Paradise (1984)   
3856      3926             Voyage to the Bottom of the Sea (1961)   
3857      3927                            Fantastic Voyage (1966)   
3858      3928       Abbott and Costello Meet Frankenstein (1948)   
3859      3929                              Bank Dick, The (1940)   
3860      3930         Creature From the Black Lagoon, The (1954)   
3861      3931                     Giant Gila Monster, The (1959)   
3862      3932                          Invisible Man, The (1933)   
3863      3933                          Killer Shrews, The (1959)   
3864      3934                                      Kronos (1957)   
3865      3935                                      Kronos (1973)   
3866      3936                   Phantom of the Opera, The (1943)   
3867      3937                                     Runaway (1984)   
3868      3938                 Slumber Party Massacre, The (1982)   
3869      3939              Slumber Party Massacre II, The (1987)   
3870      3940             Slumber Party Massacre III, The (1990)   
3871      3941                     Sorority House Massacre (1986)   
3872      3942                  Sorority House Massacre II (1990)   
3873      3943                                  Bamboozled (2000)   
3874      3944                                     Bootmen (2000)   
3875      3945                          Digimon: The Movie (2000)   
3876      3946                                  Get Carter (2000)   
3877      3947                                  Get Carter (1971)   
3878      3948                            Meet the Parents (2000)   
3879

In [88]:
movies_windic.ix[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [89]:
# 对于很大的数据，这种方法构建指标非常慢。肯定需要编写一个能够利用DataFrame内部机制的更低级的函数才行 
# 一个对统计应用的秘诀是：结合get_dummies和诸如cut之类的离散化函数
np.random.seed(12345)

In [90]:
values = np.random.rand(10)
values

array([ 0.92961609,  0.31637555,  0.18391881,  0.20456028,  0.56772503,
        0.5955447 ,  0.96451452,  0.6531771 ,  0.74890664,  0.65356987])

In [91]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1]
0         0           0           0           0         1
1         0           1           0           0         0
2         1           0           0           0         0
3         0           1           0           0         0
4         0           0           1           0         0
5         0           0           1           0         0
6         0           0           0           0         1
7         0           0           0           1         0
8         0           0           0           1         0
9         0           0           0           1         0